name: Auto Update SCTV Token

on:
  schedule:
    - cron: '0 */2 * * *' # Cứ 2 tiếng chạy 1 lần
  workflow_dispatch:      # Nút để bạn bấm chạy tay

jobs:
  update-link:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install requests
        run: pip install requests

      - name: Run script
        run: python get_link.py

      - name: Push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add sctv_auto.m3u
          git commit -m "Auto update token" || exit 0
          git push
